/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dreamhut;

import javax.swing.JOptionPane;



/**
 *
 * @author patamayo
 */
public class IntApartment extends javax.swing.JFrame {

    /**
     * Creates new form IntApartament
     */
    public IntApartment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlnumber = new javax.swing.JLabel();
        jltower = new javax.swing.JLabel();
        jlproperty = new javax.swing.JLabel();
        jbregister = new javax.swing.JButton();
        jbaward = new javax.swing.JButton();
        jbsearch = new javax.swing.JButton();
        jbreturn = new javax.swing.JButton();
        jtfnumber = new javax.swing.JTextField();
        jtftower = new javax.swing.JTextField();
        jcbowner = new javax.swing.JComboBox<>();
        jbdelete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtfarea = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("APARTMENT");

        jlnumber.setText("Number");

        jltower.setText("Tower");

        jlproperty.setText("Owner");

        jbregister.setText("Register");
        jbregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbregisterActionPerformed(evt);
            }
        });

        jbaward.setText("Award");
        jbaward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbawardActionPerformed(evt);
            }
        });

        jbsearch.setText("Search");
        jbsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsearchActionPerformed(evt);
            }
        });

        jbreturn.setText("Return");
        jbreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbreturnActionPerformed(evt);
            }
        });

        jbdelete.setText("Delete");
        jbdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbdeleteActionPerformed(evt);
            }
        });

        jLabel2.setText("Area");

        jtfarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfareaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlnumber)
                            .addComponent(jltower)
                            .addComponent(jlproperty))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfnumber)
                            .addComponent(jtftower)
                            .addComponent(jcbowner, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbsearch)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(48, 48, 48)
                                .addComponent(jtfarea))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbregister)
                                .addGap(31, 31, 31)
                                .addComponent(jbaward)
                                .addGap(18, 18, 18)
                                .addComponent(jbdelete)
                                .addGap(18, 18, 18)
                                .addComponent(jbreturn)))
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlnumber)
                    .addComponent(jtfnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbsearch))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jltower)
                    .addComponent(jtftower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlproperty)
                    .addComponent(jcbowner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbregister)
                    .addComponent(jbaward)
                    .addComponent(jbdelete)
                    .addComponent(jbreturn))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbreturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbreturnActionPerformed

    private void jbdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbdeleteActionPerformed
        // TODO add your handling code here:
        int number = Integer.parseInt(jtfnumber.getText());
        int tower = Integer.parseInt(jtftower.getText());
        if(IntDreamHutMain.getDhm().getApartments().Remove(number, tower))
        {
            JOptionPane.showMessageDialog(null, "Deleted apartment");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "ERROR");
        }
        Clear();
    }//GEN-LAST:event_jbdeleteActionPerformed

    private void jtfareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfareaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jcbowner.removeAllItems();
        Node aux = IntDreamHutMain.getDhm().getOwners().getFirst();
        while(aux!=null)
        {
            jcbowner.addItem(((Owner)aux.getData()).getId());
            aux=aux.getLink();
        }
    }//GEN-LAST:event_formWindowOpened

    private void jbregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbregisterActionPerformed
        // TODO add your handling code here:
        int number = Integer.parseInt(jtfnumber.getText());
        int tower = Integer.parseInt(jtftower.getText());
        double area = Double.parseDouble(jtfarea.getText());
        
        if(number!=0 && tower!=0 && area!=0)
        {
            Apartment ap = new Apartment(number, tower, area);
            IntDreamHutMain.getDhm().getApartments().AddLast(ap);
            JOptionPane.showMessageDialog(null, "Created apartment");
            Clear();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "incompleted information");
        }
        Clear();
    }//GEN-LAST:event_jbregisterActionPerformed

    private void jbsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsearchActionPerformed
        // TODO add your handling code here:
        int number = Integer.parseInt(jtfnumber.getText());
        int tower = Integer.parseInt(jtftower.getText());
        if(number!=0 && tower!=0)
        {
            Apartment ap= IntDreamHutMain.getDhm().getApartments().Search(number, tower);
            if(ap==null)
            {
                jtfnumber.setEnabled(false);
                jtftower.setEnabled(false);
                jcbowner.setEnabled(false);
                jtfarea.setEnabled(true);
                jbregister.setEnabled(true);
                jbaward.setEnabled(false);
                jbdelete.setEnabled(false);
            }
            else
            {
                jtfarea.setText(String.valueOf(ap.getArea()));
                if(ap.getOwner()!=null)
                {
                    jcbowner.setSelectedItem(ap.getOwner().getId());
                }
                else
                {
                    jcbowner.setSelectedIndex(0);
                }
                jbregister.setEnabled(false);
                jbaward.setEnabled(true);
                jbdelete.setEnabled(true);
                jcbowner.setEnabled(true);
                
            }
        }
    }//GEN-LAST:event_jbsearchActionPerformed

    private void jbawardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbawardActionPerformed
        // TODO add your handling code here:
        int number = Integer.parseInt(jtfnumber.getText());
        int tower = Integer.parseInt(jtftower.getText());
        String id = (String)jcbowner.getSelectedItem();
        Owner o = IntDreamHutMain.getDhm().getOwners().SearchOwner(id);
        if(IntDreamHutMain.getDhm().getApartments().Award(o,number,tower))
        {
            JOptionPane.showMessageDialog(null, "award property");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "ERROR");
        }
        Clear();
    }//GEN-LAST:event_jbawardActionPerformed

    public void Clear()
    {
        jtfnumber.setText("");
        jtfnumber.setEnabled(true);
        jtftower.setText("");
        jtftower.setEnabled(true);
        jcbowner.setSelectedItem(0);
        jcbowner.setEnabled(false);
        jtfarea.setText("");
        jtfarea.setEnabled(false);
        jbregister.setEnabled(false);
        jbaward.setEnabled(false);
        jbdelete.setEnabled(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntApartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntApartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntApartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntApartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntApartment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbaward;
    private javax.swing.JButton jbdelete;
    private javax.swing.JButton jbregister;
    private javax.swing.JButton jbreturn;
    private javax.swing.JButton jbsearch;
    private javax.swing.JComboBox<String> jcbowner;
    private javax.swing.JLabel jlnumber;
    private javax.swing.JLabel jlproperty;
    private javax.swing.JLabel jltower;
    private javax.swing.JTextField jtfarea;
    private javax.swing.JTextField jtfnumber;
    private javax.swing.JTextField jtftower;
    // End of variables declaration//GEN-END:variables
}
