/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dreamhut;

import javax.swing.JOptionPane;

/**
 *
 * @author patamayo
 */
public class IntOwner extends javax.swing.JFrame {

    /**
     * Creates new form Property
     */
    public IntOwner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlid = new javax.swing.JLabel();
        jlname = new javax.swing.JLabel();
        jlemail = new javax.swing.JLabel();
        jtfid = new javax.swing.JTextField();
        jbsearch = new javax.swing.JButton();
        jtfname = new javax.swing.JTextField();
        jtfemail = new javax.swing.JTextField();
        jbregister = new javax.swing.JButton();
        jbreturn = new javax.swing.JButton();
        jbclear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("OWNER");

        jlid.setText("ID");

        jlname.setText("Name");

        jlemail.setText("Email");

        jbsearch.setText("Search");
        jbsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsearchActionPerformed(evt);
            }
        });

        jtfname.setEnabled(false);
        jtfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfnameActionPerformed(evt);
            }
        });

        jtfemail.setEnabled(false);

        jbregister.setText("Register");
        jbregister.setEnabled(false);
        jbregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbregisterActionPerformed(evt);
            }
        });

        jbreturn.setText("Return");
        jbreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbreturnActionPerformed(evt);
            }
        });

        jbclear.setText("Clear");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbregister)
                        .addGap(36, 36, 36)
                        .addComponent(jbclear)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlid)
                            .addComponent(jlemail)
                            .addComponent(jlname))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfid)
                            .addComponent(jtfname)
                            .addComponent(jtfemail, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbsearch)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbreturn)
                        .addGap(41, 41, 41))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlid)
                    .addComponent(jtfid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbsearch))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlname)
                    .addComponent(jtfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlemail)
                    .addComponent(jtfemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbregister)
                    .addComponent(jbreturn)
                    .addComponent(jbclear))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfnameActionPerformed

    private void jbsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsearchActionPerformed
        // TODO add your handling code here:
        String id = jtfid.getText();
        if(!id.equals(""))
        {
            Owner ow=IntDreamHutMain.getDhm().getOwners().SearchOwner(id);
            if(ow == null)
            {
                jtfid.setEnabled(false);
                jtfname.setEnabled(true);
                jtfemail.setEnabled(true);
                jbregister.setEnabled(true);
            }
            else
            {
                jtfname.setText(ow.getName());
                jtfemail.setText(ow.getEmail());
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "ERROR: incompleted information");
        }
    }//GEN-LAST:event_jbsearchActionPerformed

    public void Clear()
    {
        jtfid.setText("");
        jtfid.setEnabled(true);
        jtfname.setText("");
        jtfname.setEnabled(false);
        jtfemail.setText("");
        jtfemail.setEnabled(false);
        jbregister.setEnabled(false);
    }
    private void jbregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbregisterActionPerformed
        // TODO add your handling code here:
        String id = jtfid.getText();
        String name = jtfname.getText();
        String email = jtfemail.getText();
        
        if(!id.equals("") && !name.equals("") && !email.equals(""))
        {
            Owner ow = new Owner(id, name, email);
            IntDreamHutMain.getDhm().getOwners().AddLast(ow);
            JOptionPane.showMessageDialog(null, "Created Owner");
            Clear();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "information incompleted");
        }
    }//GEN-LAST:event_jbregisterActionPerformed

    private void jbreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbreturnActionPerformed
        // TODO add your handling code here:
        IntDreamHutMain.getDhm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbreturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntOwner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbclear;
    private javax.swing.JButton jbregister;
    private javax.swing.JButton jbreturn;
    private javax.swing.JButton jbsearch;
    private javax.swing.JLabel jlemail;
    private javax.swing.JLabel jlid;
    private javax.swing.JLabel jlname;
    private javax.swing.JTextField jtfemail;
    private javax.swing.JTextField jtfid;
    private javax.swing.JTextField jtfname;
    // End of variables declaration//GEN-END:variables
}
